"""
Run this once after creating the database:
    python seed.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.db.database import SessionLocal, engine, Base
from app.models.models import User, Milestone, Task, Subtask, Question
from app.core.security import hash_password

Base.metadata.create_all(bind=engine)

MILESTONE_DATA = [
  (1, "Initiation & Requirement", [
    ("Business Understanding", "Functional Consultant", [
      ("Understand client business operations", True, [("Core business domain","text"),("Industry vertical","text"),("Key business processes","long"),("Number of locations","number"),("Key stakeholders","long"),("Business goals & KPIs","long"),("Current challenges","long"),("Expected outcome","long"),("Session reference","text"),("Additional notes","long")]),
      ("Understand organizational structure",    True, [("Organisation hierarchy","long"),("Decision-making structure","long"),("Teams interacting with system","long"),("Number of users","number"),("Reporting lines","long"),("Key contact per department","long"),("Additional notes","long")]),
      ("Understand existing software/application",True,[("Current ERP/software","text"),("Version/edition","text"),("Modules actively used","long"),("Integration points","long"),("Known limitations","long"),("Data export capability","yesno"),("API availability","yesno"),("Additional notes","long")]),
      ("Identify business pain points",          True, [("Pain point #1","long"),("Pain point #2","long"),("Pain point #3","long"),("Impact on operations","long"),("Priority level","dropdown_hml"),("Affected departments","long"),("Additional notes","long")]),
      ("Understand expected business outcome",   True, [("Expected outcome — automation","long"),("Expected outcome — reporting","long"),("Expected outcome — process","long"),("Target go-live date","date"),("Success criteria","long"),("Regulatory requirements","long"),("Additional notes","long")]),
    ]),
    ("Business Requirement", "Functional Consultant", [
      ("Conduct requirement gathering sessions", True, [("Session date","date"),("Session mode","dropdown_mode"),("Attendees client","long"),("Attendees team","long"),("Topics covered","long"),("MOM shared","yesno"),("Follow-up actions","long"),("Next session date","date")]),
      ("Capture report requirements",            True, [("Report name","text"),("Report frequency","dropdown_freq"),("Source data","text"),("Filters required","long"),("Audience","long"),("Output format","dropdown_fmt"),("Priority","dropdown_hml"),("Additional notes","long")]),
      ("Capture process automation requirements",True, [("Process name","text"),("Current manual effort (hrs/day)","number"),("Trigger condition","long"),("Expected output","long"),("Exceptions","long"),("Approval needed","yesno"),("Additional notes","long")]),
      ("Capture approval workflow requirements", True, [("Transaction type","text"),("Number of approval levels","number"),("Level 1 approver","text"),("Level 2 approver","text"),("Escalation logic","long"),("Time limit (hours)","number"),("Rejection handling","long"),("Email trigger required","yesno"),("Additional notes","long")]),
      ("Capture KPI and dashboard requirements", True, [("KPI name","text"),("Calculation logic","long"),("Data source","text"),("Refresh frequency","dropdown_freq"),("Target threshold","text"),("Dashboard type","dropdown_dash"),("Audience","long"),("Additional notes","long")]),
      ("Document business requirements",         True, [("BRD document version","text"),("BRD prepared by","text"),("BRD reviewed by","text"),("BRD approval status","dropdown_rev"),("BRD approval date","date"),("Requirements count","number"),("Open items","long"),("Additional notes","long")]),
      ("Document features list",                 True, [("Mail trigger condition","long"),("Mail recipients","long"),("User access roles defined","yesno"),("Access matrix attached","yesno"),("Alert trigger condition","long"),("Alert channel","dropdown_alert"),("Additional notes","long")]),
    ]),
    ("Initial Study", "Functional Consultant", [
      ("Analyze existing process flow",  True, [("Process name","text"),("Process owner","text"),("AS-IS documented","yesno"),("Flow diagram available","yesno"),("Bottlenecks","long"),("Number of manual steps","number"),("Frequency","dropdown_freq"),("Additional notes","long")]),
      ("Analyze current reports",        True, [("Report name","text"),("Generated by","dropdown_gen"),("Frequency","dropdown_freq"),("Key fields","long"),("Accuracy issues","yesno"),("Report audience","long"),("Action needed","dropdown_action"),("Additional notes","long")]),
      ("Review source systems",          True, [("Source system name","text"),("Data available","yesno"),("Export method","dropdown_export"),("Data quality issues","yesno"),("Data quality notes","long"),("Access granted","yesno"),("Additional notes","long")]),
      ("Study available master data",    True, [("Master data entity","text"),("Data source","text"),("Completeness (%)","number"),("Cleansing required","yesno"),("Responsible team","text"),("Additional notes","long")]),
      ("Identify gaps",                  True, [("Gap #1","long"),("Gap #2","long"),("Gap #3","long"),("Gap impact","dropdown_hml"),("Recommended resolution","long"),("Additional notes","long")]),
      ("Identify manual activities",     True, [("Activity name","text"),("Department","text"),("Frequency","dropdown_freq"),("Time per execution (hrs)","number"),("Automation feasibility","dropdown_yn_p"),("Priority","dropdown_hml"),("Additional notes","long")]),
    ]),
    ("Scope Defining", "Functional Consultant & Technical Team", [
      ("Define reports to be developed",   True, [("Report #","number"),("Report name","text"),("Source module","text"),("Complexity","dropdown_hml"),("Estimated effort (days)","number"),("Priority","dropdown_hml"),("Notes","long")]),
      ("Define dashboards to be developed",True, [("Dashboard name","text"),("Key metrics","long"),("Target audience","text"),("Technology","text"),("Estimated effort (days)","number"),("Notes","long")]),
      ("Define automation scope",          True, [("Automation name","text"),("Type","dropdown_auto"),("Estimated effort (days)","number"),("Dependencies","long"),("Notes","long")]),
      ("Define integrations required",     True, [("Integration name","text"),("Source system","text"),("Target system","text"),("Integration type","dropdown_int"),("Frequency","dropdown_freq"),("Estimated effort (days)","number"),("Notes","long")]),
      ("Define exclusions",               True, [("Exclusion #1","long"),("Exclusion #2","long"),("Exclusion #3","long"),("Reason","long"),("Agreed with client","yesno"),("Notes","long")]),
      ("Estimate effort and timeline",    True, [("Total mandays","number"),("Project start date","date"),("Planned go-live date","date"),("Buffer (days)","number"),("Effort doc attached","yesno"),("Notes","long")]),
    ]),
    ("Scope Finalization", "Functional Consultant", [
      ("Review scope internally",  True, [("Internal review done","yesno"),("Review date","date"),("Reviewers","long"),("Comments","long"),("Final doc version","text"),("Notes","long")]),
      ("Review scope with client", True, [("Client review date","date"),("Client attendees","long"),("Client feedback","long"),("Changes requested","long"),("Revised doc shared","yesno"),("Notes","long")]),
      ("Clarify open points",      True, [("Open point #1","long"),("Resolution #1","long"),("Open point #2","long"),("Resolution #2","long"),("All resolved","yesno"),("Notes","long")]),
      ("Freeze project scope",     True, [("Scope freeze date","date"),("Client acknowledged","yesno"),("SPOC name","text"),("SPOC sign-off","yesno"),("Change control agreed","yesno"),("Notes","long")]),
    ]),
    ("Client Confirmation", "Functional Consultant", [
      ("Present finalized scope", False, "date"),
      ("Obtain scope approval",   False, "yesno"),
      ("Obtain advance from client", False, "yesno"),
    ]),
  ]),
  (2, "Kick Off", [
    ("Kick Off Meeting with Client", "Functional Consultant", [
      ("Introduce project team",       True, [("PM name","text"),("FC name","text"),("Tech lead name","text"),("Other members","long"),("Client SPOC name","text"),("Introduction completed","yesno"),("Notes","long")]),
      ("Discuss project scope",        True, [("Scope doc version","text"),("Key scope items","long"),("Client queries","long"),("Scope accepted","yesno"),("Action items","long"),("Notes","long")]),
      ("Discuss timelines",            True, [("Project start date","date"),("Go-live date","date"),("Milestone timeline shared","yesno"),("Client agreed","yesno"),("Timeline doc attached","yesno"),("Notes","long")]),
      ("Discuss dependencies",         True, [("Dependency #1","long"),("Owner #1","text"),("Dependency #2","long"),("Owner #2","text"),("Client dependencies","yesno"),("Risk notes","long"),("Notes","long")]),
      ("Finalize communication process",True,[("Primary channel","text"),("Meeting frequency","dropdown_freq"),("Status report frequency","dropdown_freq"),("Escalation matrix","yesno"),("Client SPOC","text"),("Team SPOC","text"),("Comm plan shared","yesno"),("Notes","long")]),
      ("Share MOM",                    True, [("Meeting date","date"),("MOM prepared by","text"),("MOM shared date","date"),("MOM shared via","text"),("Client acknowledged","yesno"),("Action items","long"),("Next meeting date","date"),("Notes","long")]),
    ]),
  ]),
  (3, "Process Study", [
    ("Detailed Process Study", "Functional Consultant", [
      ("Conduct department-wise discussions",True,[("Department name","text"),("Discussion date","date"),("Representative","text"),("Topics discussed","long"),("Pain points","long"),("MOM shared","yesno"),("Follow-up required","yesno"),("Notes","long")]),
      ("Understand AS-IS process",          True,[("Process name","text"),("Process owner","text"),("Start trigger","long"),("End condition","long"),("Number of steps","number"),("AS-IS diagram created","yesno"),("Process frequency","dropdown_freq"),("Pain points","long"),("Notes","long")]),
      ("Capture transaction flow",          True,[("Transaction name","text"),("Originating module","text"),("Transaction steps","long"),("Data fields","long"),("System validations","long"),("Output/result","long"),("Error handling","yesno"),("Notes","long")]),
      ("Capture approval flow",             True,[("Transaction requiring approval","text"),("Approval level 1","text"),("Approval level 2","text"),("Approval level 3","text"),("Auto-approval conditions","long"),("Rejection handling","long"),("Notification trigger","yesno"),("Time limit (hours)","number"),("Notes","long")]),
      ("Capture exception scenarios",       True,[("Exception #1","long"),("Handling #1","long"),("Exception #2","long"),("Handling #2","long"),("Exception #3","long"),("Handling #3","long"),("All documented","yesno"),("Notes","long")]),
      ("Capture business rules",            True,[("Rule #1","long"),("Rule #1 trigger","long"),("Rule #2","long"),("Rule #2 trigger","long"),("Rule #3","long"),("Rule #3 trigger","long"),("Validated with client","yesno"),("Notes","long")]),
    ]),
    ("Process Documentation", "Functional Consultant", [
      ("Prepare process flow diagrams",True,[("Process name","text"),("Tool used","text"),("Diagram created","yesno"),("Reviewed internally","yesno"),("Shared with client","yesno"),("Client feedback","long"),("Diagram version","text"),("Notes","long")]),
      ("Document TO-BE process",       True,[("Process name","text"),("TO-BE owner","text"),("Key changes from AS-IS","long"),("TO-BE diagram created","yesno"),("TO-BE steps","long"),("Automation points","long"),("Client approved","yesno"),("Doc version","text"),("Notes","long")]),
      ("Document business rules",      True,[("Module/area","text"),("Total rules count","number"),("Doc version","text"),("Reviewed with client","yesno"),("Exceptions noted","long"),("Doc shared date","date"),("Notes","long")]),
      ("Document validations",         True,[("Validation name","text"),("Type","text"),("Field name","text"),("Validation logic","long"),("Error message","text"),("Reviewed by","text"),("Approved","yesno"),("Notes","long")]),
      ("Document report logic",        True,[("Report name","text"),("Source data","text"),("Filters/parameters","long"),("Calculation logic","long"),("Output columns","long"),("Sorting/grouping","long"),("Reviewed","yesno"),("Notes","long")]),
    ]),
    ("Process Confirmation", "Functional Consultant", [
      ("Walkthrough documentation with users",True,[("Walkthrough date","date"),("Users attended","long"),("Doc version","text"),("Feedback received","long"),("Revisions requested","number"),("Revised version","text"),("Sign-off obtained","yesno"),("Notes","long")]),
      ("Resolve comments",                    True,[("Comment #1","long"),("Resolution #1","long"),("Comment #2","long"),("Resolution #2","long"),("Comment #3","long"),("Resolution #3","long"),("All resolved","yesno"),("Notes","long")]),
      ("Update process documents",            True,[("Doc name updated","text"),("Updated version","text"),("Changes made","long"),("Shared date","date"),("Client acknowledged","yesno"),("Notes","long")]),
      ("Obtain process sign-off",             True,[("Sign-off doc name","text"),("Sign-off date","date"),("Signed by (client)","text"),("Role of signatory","text"),("Sign-off method","text"),("Doc stored","yesno"),("Notes","long")]),
    ]),
  ]),
  (4, "Requirement Specification", [
    ("FRD to Technical Team", "Functional Consultant", [
      ("Prepare FRD",              True,[("FRD doc name","text"),("FRD version","text"),("FRD author","text"),("FRD created date","date"),("Total sections","number"),("Internal review done","yesno"),("Shared with tech team","yesno"),("Notes","long")]),
      ("Define input sources",     True,[("Source #1 name","text"),("Source #1 system","text"),("Source #1 format","dropdown_export"),("Source #2 name","text"),("Source #2 system","text"),("Source #3 name","text"),("All access confirmed","yesno"),("Notes","long")]),
      ("Define output requirements",True,[("Output #1 name","text"),("Output #1 type","text"),("Output #1 frequency","dropdown_freq"),("Output #1 audience","text"),("Output #2 name","text"),("Output #2 type","text"),("Output format","dropdown_fmt"),("Notes","long")]),
      ("Define calculations",       True,[("Calculation name","text"),("Formula/logic","long"),("Input fields","long"),("Output field","text"),("Edge cases","long"),("Verified with client","yesno"),("Notes","long")]),
      ("Define business validations",True,[("Validation name","text"),("Field name","text"),("Validation rule","long"),("Error message","text"),("Type","text"),("Approved","yesno"),("Notes","long")]),
      ("Define report layouts",     True,[("Report name","text"),("Number of columns","number"),("Column names","long"),("Grouping/subtotals","long"),("Header/footer","long"),("Sample layout attached","yesno"),("Layout approved","yesno"),("Notes","long")]),
      ("Obtain FRD approval - Internal", False, "yesno"),
    ]),
    ("Plan, Approach, Architecture", "Functional Consultant", [
      ("Design technical solution",          True,[("Architecture approach","long"),("Technology stack","long"),("Database platform","text"),("Server environment","dropdown_deploy"),("Third-party integrations","long"),("Solution doc created","yesno"),("Internal review done","yesno"),("Notes","long")]),
      ("Define database approach",           True,[("Database platform","text"),("Database name","text"),("Schema design","long"),("Key tables","long"),("Indexing strategy","long"),("Data archival approach","long"),("DB design reviewed","yesno"),("Notes","long")]),
      ("Define data flow",                   True,[("Data flow diagram created","yesno"),("Source systems","long"),("Transformation logic","long"),("Target destination","text"),("Real-time or batch","dropdown_auto"),("Volume (records/day)","number"),("Data flow reviewed","yesno"),("Notes","long")]),
      ("Define deployment approach",         True,[("Deployment environment","dropdown_deploy"),("Deployment method","text"),("CI/CD required","yesno"),("Rollback plan","yesno"),("Deployment checklist","yesno"),("Notes","long")]),
      ("Finalize development plan (Timeline, Mandays)",True,[("Total mandays","number"),("Dev start date","date"),("Planned completion","date"),("Buffer (days)","number"),("Resource allocation defined","yesno"),("Plan shared","yesno"),("Plan approved","yesno"),("Notes","long")]),
    ]),
  ]),
  (5, "Development", [
    ("Development", "Technical Team", [
      ("Database object creation",    True,[("DB name","text"),("Tables created","number"),("Views created","number"),("Stored procedures","number"),("Indexes created","yesno"),("DB script reviewed","yesno"),("Deployed to dev","yesno"),("Notes","long")]),
      ("Data extraction development", True,[("Data source","text"),("Extraction method","dropdown_export"),("Extraction frequency","dropdown_freq"),("Fields extracted","long"),("Transformation applied","long"),("Error handling","yesno"),("Extraction tested","yesno"),("Notes","long")]),
      ("Business logic development",  True,[("Module name","text"),("Business logic","long"),("Rules implemented","long"),("Edge cases handled","long"),("Unit tested","yesno"),("Code reviewed","yesno"),("Notes","long")]),
      ("Report development",          True,[("Report name","text"),("Report type","text"),("Data source/query","text"),("Filters implemented","long"),("Calculations verified","long"),("Report format","dropdown_fmt"),("Unit tested","yesno"),("Notes","long")]),
      ("Dashboard development",       True,[("Dashboard name","text"),("Dashboard type","dropdown_dash"),("KPIs displayed","long"),("Refresh frequency","dropdown_freq"),("Charts/visuals","long"),("Mobile responsive","yesno"),("Unit tested","yesno"),("Notes","long")]),
      ("Validation implementation",   True,[("Validation name","text"),("Field/module","text"),("Validation rule","long"),("Error message","text"),("Test case passed","yesno"),("Notes","long")]),
      ("Internal developer testing",  True,[("Test date","date"),("Modules tested","long"),("Test cases executed","number"),("Issues found","number"),("Issues resolved","yesno"),("Retest completed","yesno"),("Notes","long")]),
      ("Bug fixing",                  True,[("Bug ID","text"),("Bug description","long"),("Severity","dropdown_sev"),("Root cause","long"),("Fix applied","long"),("Fix tested","yesno"),("Bug closed","yesno"),("Notes","long")]),
    ]),
  ]),
  (6, "Internal Testing", [
    ("Internal Testing", "Technical Team & Functional Team", [
      ("Prepare test scenarios",  True,[("Module name","text"),("Scenarios count","number"),("Doc version","text"),("Reviewed","yesno"),("Edge cases included","yesno"),("Negative scenarios","yesno"),("Notes","long")]),
      ("Validate business rules", True,[("Rule name","text"),("Test case","long"),("Expected result","long"),("Actual result","long"),("Test result","dropdown_test"),("Defect raised","yesno"),("Defect ID","text"),("Notes","long")]),
      ("Validate calculations",   True,[("Calculation name","text"),("Input values","long"),("Expected output","text"),("Actual output","text"),("Variance","text"),("Test result","dropdown_test"),("Defect raised","yesno"),("Notes","long")]),
      ("Validate report outputs", True,[("Report name","text"),("Test data","long"),("Expected output","long"),("Actual output","long"),("Column count matched","yesno"),("Accuracy verified","yesno"),("Test result","dropdown_test"),("Defect ID","text"),("Notes","long")]),
      ("Validate dashboard outputs",True,[("Dashboard name","text"),("KPI name","text"),("Expected value","text"),("Actual value","text"),("Variance","text"),("Rendering correct","yesno"),("Test result","dropdown_test"),("Notes","long")]),
      ("Log defects",             True,[("Defect ID","text"),("Defect title","text"),("Module affected","text"),("Severity","dropdown_sev"),("Steps to reproduce","long"),("Expected vs actual","long"),("Assigned to","text"),("Status","dropdown_closure"),("Notes","long")]),
      ("Retest fixes",            True,[("Defect ID retested","text"),("Fix description","long"),("Retest date","date"),("Retest result","dropdown_test"),("Defect closed","yesno"),("Regression impact checked","yesno"),("Notes","long")]),
      ("Internal testing sign-off", False, "yesno"),
    ]),
  ]),
  (7, "Deployment", [
    ("Deployment for UAT", "Technical Team", [
      ("Server Readiness",                  False, "yesno"),
      ("Master data Deploy",               False, "yesno"),
      ("Deploy solution to UAT environment",False, "date"),
      ("Load sample data",                 False, "yesno"),
      ("Share UAT version",                False, "yesno"),
    ]),
    ("Post Deployment testing", "Technical Team", [
      ("Execute smoke testing", False, "dropdown_pf"),
      ("Verify deployment",    False, "dropdown_pf"),
    ]),
  ]),
  (8, "UAT", [
    ("UAT for End User", "Technical Team", [
      ("Provide user training",    False, "yesno"),
      ("Conduct UAT walkthrough",  True, [("Walkthrough date","date"),("Users attended","long"),("Modules covered","long"),("User queries","long"),("Queries resolved","yesno"),("Follow-up actions","long"),("Walkthrough feedback","long"),("Notes","long")]),
      ("Execute user test cases",  True, [("Test case ID","text"),("Description","long"),("Tested by","text"),("Test date","date"),("Expected result","long"),("Actual result","long"),("Test result","dropdown_test"),("Defect raised","yesno"),("Notes","long")]),
      ("Validate outputs",         True, [("Output name","text"),("Validated by","text"),("Validation date","date"),("Matches expectation","yesno"),("Issues noted","long"),("Accepted by user","yesno"),("Notes","long")]),
      ("Validate business scenarios",True,[("Scenario name","text"),("Description","long"),("Data used","long"),("Expected outcome","long"),("Actual outcome","long"),("Scenario passed","yesno"),("Defect raised","yesno"),("Notes","long")]),
      ("Log UAT observations",     True, [("Observation ID","text"),("Module","text"),("Description","long"),("Severity","dropdown_sev"),("Raised by","text"),("Status","dropdown_closure"),("Resolution","long"),("Notes","long")]),
      ("Fix UAT defects",          True, [("Defect ID","text"),("Description","long"),("Fixed by","text"),("Fix date","date"),("Fix description","long"),("Retest required","yesno"),("Defect closed","yesno"),("Notes","long")]),
      ("Re-deploy updated version",True, [("Version number","text"),("Deployment date","date"),("Environment","text"),("Changes included","long"),("Deployment verified","yesno"),("Users notified","yesno"),("Notes","long")]),
      ("Obtain UAT sign-off",      False, "yesno"),
    ]),
  ]),
  (9, "Go Live", [
    ("Go Live", "Technical Team", [
      ("Deploy production version",       True,[("Production date","date"),("Deployed version","text"),("Deployed by","text"),("Deployment method","text"),("Downtime required","yesno"),("Downtime duration (hrs)","number"),("Deployment successful","yesno"),("Notes","long")]),
      ("Configure production environment",True,[("Server/env name","text"),("Config checklist","long"),("Database configured","yesno"),("Connections configured","yesno"),("SSL/security configured","yesno"),("Config verified","yesno"),("Notes","long")]),
      ("Validate production data",        True,[("Validation date","date"),("Master data loaded","yesno"),("Opening balances verified","yesno"),("Historical data migrated","yesno"),("Accuracy checked","yesno"),("Data validation sign-off","yesno"),("Notes","long")]),
      ("Perform sanity testing",          True,[("Test date","date"),("Modules tested","long"),("Test cases executed","number"),("Test result","dropdown_pf"),("Critical issues found","yesno"),("Issues resolved","yesno"),("Notes","long")]),
      ("Obtain go-live approval",         True,[("Approval requested date","date"),("Approved by","text"),("Approver designation","text"),("Approval method","text"),("Approval received","yesno"),("Approval stored","yesno"),("Notes","long")]),
      ("Release to users",                True,[("Go-live date","date"),("Users notified","yesno"),("Notification method","text"),("User access configured","yesno"),("Training refresher provided","yesno"),("Hypercare start date","date"),("Notes","long")]),
    ]),
  ]),
  (10, "Support", [
    ("Post Live Support", "Technical Team", [
      ("Monitor application/report", True,[("Monitoring start date","date"),("Monitoring tool","text"),("Monitoring frequency","dropdown_freq"),("Performance metrics","long"),("Alerts configured","yesno"),("Issues identified","yesno"),("Report shared","yesno"),("Notes","long")]),
      ("Resolve production issues",  True,[("Issue ID","text"),("Description","long"),("Issue type","dropdown_support"),("Priority","dropdown_priority"),("Reported by","text"),("Reported date","date"),("Resolution","long"),("Resolved date","date"),("Closed","yesno"),("Notes","long")]),
      ("Resolve user queries",       True,[("Query ID","text"),("User name","text"),("Query description","long"),("Query type","dropdown_support"),("Response provided","long"),("Resolution date","date"),("User satisfied","yesno"),("Notes","long")]),
      ("Fine tune performance",      True,[("Area of issue","text"),("Baseline performance","text"),("Optimization applied","long"),("Improved performance","text"),("Test result","dropdown_pf"),("Changes deployed","yesno"),("Notes","long")]),
      ("Handover project documents", True,[("Document name","text"),("Document version","text"),("Handed over to","text"),("Handover date","date"),("Document type","text"),("Acknowledgement received","yesno"),("Notes","long")]),
      ("Project closure",            True,[("Closure date","date"),("Closure report created","yesno"),("Lessons learned documented","yesno"),("Final sign-off obtained","yesno"),("Signed by client","text"),("Post-project review scheduled","yesno"),("Project archived","yesno"),("Notes","long")]),
    ]),
  ]),
]

def seed():
    db = SessionLocal()
    try:
        if db.query(User).count() > 0:
            print("Database already seeded. Skipping.")
            return

        # Seed users
        users = [
            User(name="Admin User",               email="admin@wbs.com", password_hash=hash_password("admin123"), role="Admin"),
            User(name="Priya Krishnan",            email="fc@wbs.com",    password_hash=hash_password("fc123"),    role="Functional Consultant"),
            User(name="Arun Dev",                  email="tech@wbs.com",  password_hash=hash_password("tech123"),  role="Technical Team"),
            User(name="Client Reviewer",           email="client@wbs.com",password_hash=hash_password("client123"),role="Client"),
        ]
        for u in users:
            db.add(u)
        print("Users seeded.")

        # Seed milestone template
        for (ms_num, ms_name, tasks) in MILESTONE_DATA:
            ms = Milestone(num=ms_num, name=ms_name)
            db.add(ms)
            db.flush()
            for t_num, (task_name, responsibility, subtasks) in enumerate(tasks, 1):
                task = Task(milestone_id=ms.id, num=t_num, name=task_name, responsibility=responsibility)
                db.add(task)
                db.flush()
                for s_num, sub_data in enumerate(subtasks, 1):
                    if len(sub_data) == 3 and isinstance(sub_data[2], str):
                        sub_name, is_fmt, input_type = sub_data
                        sub = Subtask(task_id=task.id, num=s_num, name=sub_name, is_format=False, input_type=input_type)
                        db.add(sub)
                    else:
                        sub_name, is_fmt, questions = sub_data
                        sub = Subtask(task_id=task.id, num=s_num, name=sub_name, is_format=True, input_type="text")
                        db.add(sub)
                        db.flush()
                        for q_num, (q_text, q_type) in enumerate(questions, 1):
                            q = Question(subtask_id=sub.id, num=q_num, question_text=q_text, input_type=q_type)
                            db.add(q)
            print(f"  Milestone {ms_num:02d} — {ms_name} seeded.")

        db.commit()
        print("\nSeed complete!")
        print("Login with: admin@wbs.com / admin123")
    except Exception as e:
        db.rollback()
        print(f"Seed error: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed()
